### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by melobern** [faboussard/42_minishell#104]
exit_command_not_found(t_minishell *m, char *name, t_process_list *pl); :ok: :heavy_check_mark: 
check_path (paths.c:50); :ok: :heavy_check_mark:

**Comment by faboussard** [comment]
pour regler ca ? 
>>>  Minishell>$ dg
dg: command not found
==247758== 
==247758== FILE DESCRIPTORS: 3 open (3 std) at exit.
==247758== 
==247758== HEAP SUMMARY:
==247758==     in use at exit: 204,231 bytes in 223 blocks
==247758==   total heap usage: 848 allocs, 625 frees, 271,779 bytes allocated
==247758== 
==247758== 3 bytes in 1 blocks are still reachable in loss record 2 of 64
==247758==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==247758==    by 0x40D099: ft_strdup (ft_strdup.c:21)
==247758==    by 0x40B3B3: check_path (paths.c:50)
==247758==    by 0x40B31A: set_good_path_cmd (paths.c:96)
==247758==    by 0x40A3FD: my_execve (exec.c:119)
==247758==    by 0x40A82C: exec_one_cmd (exec.c:246)
==247758==    by 0x40A6F0: execute_cmds (exec.c:265)
==247758==    by 0x4015C1: minishell_non_interactive (main.c:67)
==247758==    by 0x401895: main (main.c:143)
