### ISSUE TITLE
permission denied si juste token vide

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell#61]
>>>  Minishell>$ " "
 minishell: : Permission denied

**Comment by melobern** [comment]
Je ne l'ai pas vu afficher ca, je vois que notre autre issue est plutot que l'exec ne recoit pas la chaine " " comme commande dans la cmd_table quand il ný a que ca, ni comme argument quand c'est un argument (style cd " ", cat " ", echo " ").
En tout cas, doublon (inversé ?) de l'issue https://github.com/faboussard/42_minishell/issues/76 donc je ferme 🔐
