### ISSUE TITLE
free invalid pointer qui semble etre sur envp table, si je fais une multitude de commandes

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell#72]
>>>  Minishell>$ 
>>>  Minishell>$ 
>>>  Minishell>$ 
>>>  Minishell>$ 
>>>  Minishell>$ sgfgf dhg 
sgfgf: command not found
>>>  Minishell>$ ?G gfdh
?G: command not found
>>>  Minishell>$ 
>>>  Minishell>$ |||||||||||||||||||||||||||||||||||????????            ||||||||||||||||||||||||||||||||||
minishell: syntax error near unexpected token `|'
free(): invalid pointer
[1]    78936 IOT instruction (core dumped)  ./minishell

**Comment by melobern** [comment]
Je ne vois plus ce bug depuis mes changements sur l'exec (je suppose depuis mes safe_free qui checkent correctement maintenant). Si tu revois l'issue, tu peux toujours la réouvrir
