### ISSUE TITLE
>>>  Minishell>$ " " - > naffiche rien . ca doit afficher . ESPACE : command not  found

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell#76]

**Comment by faboussard** [comment]
maintenant on redefinit un token name vide sur "''" sil nest pas precede dune commande ou dun operateur de redirection . du coup pas detecte par un operateur de redirection mais cest mieux plutot que de creer des fichiers vides ..

**Comment by melobern** [comment]
Si un ou plusieurs espaces sont entre guillemets il faut qu'il soit considéré comme un mot. Il est tout à fait possible de créer des fichiers et dossiers nommés espaces, et bash met "command not found" car il le prend comme une commande.

**Comment by faboussard** [comment]
tu as un autre commande ? pour la commande citee notre minishell se comporte comme bash 
❯ ls > ""
bash: : Aucun fichier ou dossier de ce type

>>>  Minishell>$ ls > ""
minishell: : No such file or directory

**Comment by melobern** [comment]
Ce n'est pas `ls > ""` mais `ls > " " `

**Comment by faboussard** [comment]
et bien ca marche bien de ce que je teste ^ ^
que veux tu ^ ^

**Comment by melobern** [comment]
Sur ta branche, pas sur la mienne :D Je clos du coup^^
