### ISSUE TITLE
pour discussion a loral : necessqire de faire des ifndef partout ? pour moi cest pas necessaire

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell#80]
#ifndef MINISHELL_H
# define MINISHELL_H

# ifndef MALLOC_FAILED
#  define MALLOC_FAILED -1
# endif

# ifndef SUCCESSFULLY_ADDED
#  define SUCCESSFULLY_ADDED 0
# endif

# ifndef HERE_DOC_TMP_FILE
#  define HERE_DOC_TMP_FILE "/tmp/.tmp_heredoc"
# endif

# ifndef PATH_MAX
#  define PATH_MAX 4096
# endif

# ifndef SHLVL
#   define SHLVL_LIMIT 1000
# endif

**Comment by melobern** [comment]
➡️ Considéré comme une bonne pratique de toujours mettre ifndef même si dans un seul fichier header
➡️ Certains sont vraiment nécessaires même si uniquement dans ce projet, comme le ifndef PATH_MAX
➡️ Ceux-ci n'empêchent pas le projet de fonctionner, il vaut mieux réfléchir sur d'autres issues (notamment le Ctrl \ sur une entree standard, pour lequel le minishell rentre dans WIFEXITED au lieu de WIFSIGNALED)


![Screenshot_20240508-185123.png](https://github.com/faboussard/42_minishell/assets/46427692/28498abd-22b7-47c8-ab83-cf42a0323bc6)
