### ISSUE TITLE
Handle infile outfile
Gestion de plusieurs fichiers de sortie

### ISSUE THREAD

**Issue by melobern** [faboussard/42_minishell#82]
## Gestion de plusieurs fichiers d'entrée et de sortie non prête.
:dart: Si plusieurs fichiers d'entrée, doit vérifier qu'ils existent tous/ont tous des droits de lecture.
:dart: Si plusieurs fichiers de sortie sont attendus, le système doit créer des fichiers vides pour chaque sortie.

Besoins :
:arrow_right: liste infiles sur laquelle itérer.
:arrow_right: liste outfiles sur laquelle itérer.

Actuellement : les token_list infile et outfile contiennent uniquement celui qui est utilisé :warning:  

### Mélodie
:arrow_right:  handle infile outfile pour qu'il vérifie l'existence et les droits de lecture de tous les fichiers d'entrée :construction: 
:arrow_right: handle infile outfile pour qu'il crée tous les fichiers, comme prévu, selon la réussite de la commande du pipe concerné :microscope: test à effectuer quand token_list_outfiles complète :microscope: 

### Fanny
:arrow_right:  revoir la création de la token_list infiles :construction:  done :heavy_check_mark: 
:arrow_right:  revoir la création de la token_list outfiles :construction:  done :heavy_check_mark:

**Comment by faboussard** [comment]
cest bon PL a ete modifiee : 
Fanny

➡️ revoir la création de la token_list infiles 🚧 -- >  done ✔️
➡️ revoir la création de la token_list outfiles 🚧 --> done ✔️

**Comment by faboussard** [comment]
*sur la branche parsing , pas merged sur master car segfault a lexec

**Comment by melobern** [comment]
![image](https://github.com/faboussard/42_minishell/assets/46427692/a1e2208f-20d3-485e-b178-027a336db7d0)
Soucis d'assignation de l'**e_type** : devrait être `INFILE` ou `DELIMITER` si heredoc :scroll:

**Comment by faboussard** [comment]
repaired :)

**Comment by faboussard** [comment]
Redirection
• Execute commands with redirections < and/or >
• Repeat multiple times with different commands and arguments and sometimes change > with >>
• Check if multiple tries of the same redirections fail.
• Test << redirection (it doesn't have to update the history).
