### ISSUE TITLE
pb memoire >>>  Minishell>$ echo fdg | dfg | dfg dfg: command not found �: command not found

### ISSUE THREAD

**Issue by faboussard** [faboussard/42_minishell#91]

**Comment by melobern** [comment]
J'ai testé `echo fdg | dfg | dfg` sur les branches builtins et parsing (après avoir git pull) et je ne vois ce problème ni sur parsing ni sur builtin.
![image](https://github.com/faboussard/42_minishell/assets/46427692/27cfcfaa-540c-4aa5-92fa-935793255d80)

**Comment by faboussard** [comment]
ok tout fonctionne bien ce matin ! je voyais ce pb sur toutes les branches depuis mon pc perso portable, je lavais utilise toute la journee je pense que sa memoire commencait a saturer :) cool ! je close
